# Generated by Django 4.2.2 on 2024-05-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_number', models.CharField(max_length=2)),
                ('ep_title', models.CharField(max_length=255)),
                ('eng_plot', models.CharField(max_length=1000, null=True)),
                ('tw_plot', models.CharField(max_length=500, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episode.season')),
            ],
        ),
    ]
