# Generated by Django 4.2.2 on 2024-06-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=200)),
                ('introduction', models.CharField(max_length=1000)),
            ],
        ),
    ]
