# Generated by Django 4.2.2 on 2024-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='introduction',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='eng_plot',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ep_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tw_plot',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(),
        ),
    ]
