# Generated by Django 4.2.2 on 2024-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_alter_cast_img_url_alter_cast_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='introduction',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='eng_plot',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tw_plot',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
