# Generated by Django 4.2.2 on 2024-06-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_alter_cast_introduction_alter_episode_eng_plot_and_more'),
        ('episode', '0004_alter_cast_introduction_alter_episode_eng_plot_and_more'),
    ]

    operations = [
    ]
