# Generated by Django 4.2.2 on 2024-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0005_merge_20240604_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='introduction',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='eng_plot',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tw_plot',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
