# Generated by Django 4.2.2 on 2024-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0006_cast_age_cast_gender_alter_cast_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='img',
            field=models.ImageField(null=True, upload_to='uploaded_img'),
        ),
    ]
