# Generated by Django 4.2.2 on 2024-06-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0007_season_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='age',
            new_name='born_year',
        ),
    ]
